apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: job
    files:
      - db_password=../../../secrets/mysql_user_password
    literals:
      - db_username=taskapp_user
    type: Opaque

resources:
- job.yaml